// Instagram captions, one per feed or square post. Warm, plain, local. Each says what happens next.
// Hashtags come from the audience of the post (see HASHTAGS). Nothing here states a number or a claim the facts file does not hold.
export const HASHTAGS = {
  core: ['#shikshaq', '#kolkata', '#kolkatastudents'],
  parents: ['#kolkataparents', '#hometuition', '#privatetutor'],
  students: ['#studentlife', '#icse', '#cbse', '#isc'],
  tutors: ['#tuitionteacher', '#privatetutor', '#teachersofkolkata'],
};
const NEXT = 'Search at shikshaq.in.';

export const CAPTIONS = {
  H1: 'Shikshaq is where you find your tutor.\n\nConnecting every student in Kolkata to teachers. Search by subject, class, board and area, read the profile and the reviews, then message the tutor yourself on WhatsApp.\n\nClasses IV to XII. ICSE, ISC, CBSE and State board. Free for families.\n\n' + NEXT,
  H3: 'Maths, Science, English, Commerce. ICSE, ISC, CBSE and State board. Classes IV to XII.\n\nWhatever you are looking for, you filter by it on Shikshaq and then message the tutor yourself.\n\n' + NEXT,
  B2: 'Find your tutor in three steps.\n\nOne, search by subject, class, board and area. Two, read the profile and the reviews. Three, message the tutor on WhatsApp.\n\nFree for families. Show this to a parent.\n\n' + NEXT,
  B3: 'Three steps, one page. Save it and send it to a parent.\n\nSearch by subject, class, board and area. Read the profile and the reviews. Message the tutor on WhatsApp.\n\n' + NEXT,
  CH1: 'The chat at home, episode one.\n\nThe first question a parent asks is usually "another coaching centre?" The answer is no. You search, pick a tutor and message them.\n\nSend this to your parents.\n\n' + NEXT,
  CH2: 'The chat at home, episode two.\n\nShikshaq is made by AquaTerra, an NGO whose team are students. It is not a charity and not a class. It is where you find your tutor, and it is for any school student in Kolkata.\n\n' + NEXT,
  CH3: 'The chat at home, episode three.\n\nDo we pay? Shikshaq is free for families to use. Fees are between you and the tutor, and Shikshaq takes no commission.\n\n' + NEXT,
  CH4: 'The chat at home, episode four.\n\nHow will we know the tutor is good? Every tutor is checked and selected by our team, and the profile shows experience and reviews. You message first, then decide.\n\n' + NEXT,
  CH5: 'The chat at home, the last episode.\n\nWhich area? You filter by locality, so the tutor is near you. Then you send your parent the link.\n\n' + NEXT,
  PF4: 'Four lines to say to your parents. Swipe, then forward the one that fits.\n\nShikshaq is where you find your tutor.\n\n' + NEXT,
  PF5: 'A note for parents.\n\nShikshaq is where your child finds a tutor. Search by subject, class, board and area. Read the profile and the reviews. Message the tutor yourself. Free for families.\n\n' + NEXT,
  BB1: 'Every subject. Free for families. Every tutor checked and selected by our team.\n\nShikshaq is where you find your tutor.\n\n' + NEXT,
  SJ1: 'Looking for a Maths tutor in Kolkata?\n\nSearch by class, board and area, read the profile, then message the tutor yourself.\n\n' + NEXT,
  SJ2: 'Looking for a Science tutor in Kolkata?\n\nSearch by class, board and area, read the profile, then message the tutor yourself.\n\n' + NEXT,
  SJ3: 'Looking for an English tutor in Kolkata?\n\nSearch by class, board and area, read the profile, then message the tutor yourself.\n\n' + NEXT,
  SJ4: 'Looking for a Commerce tutor in Kolkata?\n\nSearch by class, board and area, read the profile, then message the tutor yourself.\n\n' + NEXT,
  SJ5: 'Looking for a Computer tutor in Kolkata?\n\nSearch by class, board and area, read the profile, then message the tutor yourself.\n\n' + NEXT,
  SJ6: 'Looking for a Hindi tutor in Kolkata?\n\nSearch by class, board and area, read the profile, then message the tutor yourself.\n\n' + NEXT,
  SJ7: 'Looking for a History tutor in Kolkata?\n\nSearch by class, board and area, read the profile, then message the tutor yourself.\n\n' + NEXT,
  SJ8: 'Looking for a Geography tutor in Kolkata?\n\nSearch by class, board and area, read the profile, then message the tutor yourself.\n\n' + NEXT,
  WM1: 'A student team, building the list Kolkata never had.\n\nShikshaq is made by AquaTerra, an NGO whose team are students. It is free for families, and it is where you find your tutor.\n\n' + NEXT,
  RV1: 'A real review from Shikshaq, quoted exactly as it was written.\n\nSearch by subject, class, board and area, then message the tutor yourself.\n\n' + NEXT,
  RV2: 'A real review from Shikshaq, quoted exactly as it was written.\n\n' + NEXT,
  RV3: 'A real review from Shikshaq, quoted exactly as it was written.\n\n' + NEXT,
  RV4: 'A real review from Shikshaq, quoted exactly as it was written.\n\n' + NEXT,
  RV5: 'A real review from Shikshaq, quoted exactly as it was written.\n\n' + NEXT,
  RV6: 'A real review from Shikshaq, quoted exactly as it was written.\n\n' + NEXT,
  RV7: 'Real reviews from Shikshaq, quoted exactly as they were written. Swipe to read more.\n\n' + NEXT,
  MT4: 'Meet a tutor on Shikshaq.\n\nPosted with their approval. Every tutor is checked and selected by our team.\n\n' + NEXT,
  MT5: 'Meet a tutor on Shikshaq.\n\nPosted with their approval. Every tutor is checked and selected by our team.\n\n' + NEXT,
  MT6: 'Meet a tutor on Shikshaq.\n\nPosted with their approval. Every tutor is checked and selected by our team.\n\n' + NEXT,
  TT1: 'Tutors: put your profile where students are searching.\n\nFill out a form. Our team checks your background. If you are selected, you are listed. It is free to list, you set your own rate, and you keep all of it.\n\nApply at shikshaq.in.',
  TT6: 'Your students are searching.\n\nPut your profile where they look. Free to list. You set your own rate. Real people message you on WhatsApp, not sold leads.\n\nApply at shikshaq.in.',
  TT7: 'For tutors: the first message a parent sends you.\n\nStudents and parents message you directly on WhatsApp from your profile.\n\nApply at shikshaq.in.',
  TT8: 'For tutors: what is your fee?\n\nOn Shikshaq you set your own rate and keep all of it. You and the parent agree it between you.\n\nApply at shikshaq.in.',
  TT9: 'For tutors: parents will ask where you teach.\n\nYour profile shows your area, so families find a tutor near them.\n\nApply at shikshaq.in.',
  RC1: 'Students: is your own tutor on Shikshaq?\n\nIf not, recommend them. The next student looking for a tutor can then find them too.\n\nRecommend at shikshaq.in.',
  CL1: 'An example week with a tutor. The slots are yours to agree with the tutor.\n\nSearch by subject, class, board and area, then message the tutor.\n\n' + NEXT,
  CL2: 'Puja break, sorted. One weak chapter, one doubt class, one rest day. Agree the slots with your tutor.\n\n' + NEXT,
  CL3: 'Before the exams: a revision slot, a doubts slot, a last check. Agree them with your tutor.\n\n' + NEXT,
  RP1: 'Four weeks of Shikshaq, in one post.\n\nShikshaq is where you find your tutor. Connecting every student in Kolkata to teachers.\n\nSearch, read, message. Then show a parent.\n\n' + NEXT,
  FQ9: 'The short answers, saved. What it is, who it is for, whether it is a charity, whether you pay.\n\nThe full set is in the FAQ highlight on our profile.\n\n' + NEXT,
};
export const AUDIENCE = { H1: 'parents', H3: 'students', B2: 'parents', B3: 'parents', CH1: 'students', CH2: 'students', CH3: 'students', CH4: 'students', CH5: 'students', PF4: 'students', PF5: 'parents', BB1: 'parents', WM1: 'parents', TT1: 'tutors', TT6: 'tutors', TT7: 'tutors', TT8: 'tutors', TT9: 'tutors', RC1: 'students', CL1: 'students', CL2: 'students', CL3: 'students', RP1: 'parents', FQ9: 'parents' };
